version: "2"

services:

  ### Base services
  web:
    extends:
      file: base-services.yml
      service: web_
  osem-static:
    extends:
      file: base-services.yml
      service: osem-static_
  api:
    extends:
      file: base-services.yml
      service: api_

  # # database
  # # Uncomment or specify in docker-compose.override.yml, if you want to run a database with the api
  # mongo:
  #   extends:
  #     file: database-services.yml
  #     service: mongo_

  # ### Additional Services
  # # mailer
  # # Uncomment or specify in docker-compose.override.yml
  # # Also configure OSEM_mailer_url in the api environment
  # mailer:
  #   extends:
  #     file: additional-services.yml
  #     service: mailer_
  # ttn-integration:
  #   extends:
  #     file: additional-services.yml
  #     service: ttn-integration_
  # mqtt-integration:
  #   extends:
  #     file: additional-services.yml
  #     service: mqtt-integration_

  # ### Utilities
  # # Uncomment or specify in docker-compose.override.yml
  # # assorted util containers
  # watchtower:
  #   extends:
  #     file: util-services.yml
  #     service: watchtower_
  # backup:
  #   extends:
  #     file: util-services.yml
  #     service: backup_

volumes:
  userimages:
    external: true
  mongo-data:
    external: true
  caddy-data:
    external: true
  frontend-assets:
    external: true

networks:
  api-front:
    driver: bridge
  api-back:
    driver: bridge
    internal: true
  api-mailer:
    driver: bridge
