version: "2"

services:
  # utilities
  watchtower:
    extends:
      file: util-services.yml
      service: watchtower_
  backup:
    extends:
      file: util-services.yml
      service: backup_

  # base services
  web:
    extends:
      file: base-services.yml
      service: web_
  osem-static:
    extends:
      file: base-services.yml
      service: osem-static_
  api:
    extends:
      file: base-services.yml
      service: api_

  # # database
  # # Uncomment this, if you want to run a database with the api
  # mongo:
  #   extends:
  #     file: database-services.yml
  #     service: mongo_

  # # mailer
  # # Uncomment this, if you want the mailer
  # # Also configure OSEM_mailer_url in the api environment
  # mailer:
  #   extends:
  #     file: mailer-services.yml
  #     service: mailer_

volumes:
  usersketches:
    external: true
  userimages:
    external: true
  mongo-data:
    external: true
  caddy-data:
    external: true
  frontend-assets:
    external: true

networks:
  api-front:
    driver: bridge
  api-back:
    driver: bridge
    internal: true
  api-mailer:
    driver: bridge
